### ISSUE TITLE
Link to titlebar documentation is dead

### ISSUE THREAD

**Issue by crystalfp** [AlexTorresDev/custom-electron-titlebar#232]
**Describe the bug**
The link at the end of [Get started](https://cet.alextrs.dev/en/docs/get-started/) page points nowhere.

**To Reproduce**
1. Go to  [Get started](https://cet.alextrs.dev/en/docs/get-started/) page
2. Click on 'Titlebar Options' at the bottom of the page
3. See 404 error

**Expected behavior**
Find documentation on how to use the package

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Electron version 25.3.2
 - Node Version 20.4.0

**Comment by mikeseese** [comment]
The same happens for the link at the bottom of the [Titlebar Options](https://cet.alextrs.dev/en/docs/titlebar-options/) page to go back to the getting-started. They seem to be going to `./<page>` which is resolving them to `/<lang>/docs/<current-page>/<next-page>`

The issue seems to be rooted at https://github.com/AlexTorresDev/cet-docs/blob/1a1ec1e143f53e96bb127007a49a5640f8f8d6d1/src/components/Navigation.astro#L22 and https://github.com/AlexTorresDev/cet-docs/blob/1a1ec1e143f53e96bb127007a49a5640f8f8d6d1/src/components/Navigation.astro#L41

and should probably be something like 

``` astro
          href={`../${previous.slug.split("/")[1]}`}
``````
