### ISSUE TITLE
Title moves to the left after resizing

### ISSUE THREAD

**Issue by waterfallwhitebread** [AlexTorresDev/custom-electron-titlebar#246]
## Problem Description

When resizing (i.e. make the window smaller) the electron app the title inside the titlebar is moving to the left. When I make the window bigger again it still sticks to the left.

## Steps to Reproduce

1. Resize the electron window

## Expected Behavior

The title should always stay in center when defined so in TitlebarOptions

## Current Behavior

The title moves to the left

## Additional Information

OS: Windows 10

**Comment by lvcabral** [comment]
I was about to open the same issue, here a GIF with the problem happening on my app:
![electron_Wm82DNSKuR](https://github.com/AlexTorresDev/custom-electron-titlebar/assets/16841645/498d1fe2-b561-450d-8bfe-6b1c15214df2)

**Comment by lvcabral** [comment]
The issue was introduced by [this commit ](https://github.com/AlexTorresDev/custom-electron-titlebar/commit/38740fcd9450b9b02654005f562a13c81bbc180e#diff-8451b2905f13b37a348a5c0fe8518fe72329a49510db92ae349e4dcb2083c5c7R543) that removed comments from the debug code that was there. The good practice is never to keep commented code, because this could always happen!

**Comment by lvcabral** [comment]
With that code commented the issue of moving left stops but now the title goes over the Menu when the window get small.
I think this code needs a major review.
![image](https://github.com/AlexTorresDev/custom-electron-titlebar/assets/16841645/8f5199dd-c9b7-4a5e-a6ed-e1989919d51c)

**Comment by waterfallwhitebread** [comment]
Can confirm it's working! Thanks a lot!!
